### ISSUE TITLE
vespcn pretrained weights

### ISSUE THREAD

**Issue by pinkpudding** [LoSealL/VideoSuperResolution#107]
Hi 

I have tried the eval.py using
python3 eval.py vespcn -t vid4 --pretrain=../Results/vespcn/save

downloaded both vid4 and vespcn through your google drive url.

However after i have run the command, the results in the ../Results/vespcn/VID4/original seems to be abit off. Understand that the vespcn pretrained model shld be in .ckpt however after extraction i've the following files
1. checkpoint
2. vespcn-sc4-ep1000.ckpt.data-00000-of-00001
3. vespcn-sc4-ep1000.ckpt.index
4. vespcn-sc4-ep1000.ckpt.meta

is my command and the extracted files correct?

**Comment by LoSealL** [comment]
`python eval.py vespcn -t vid4 --pretrain ../Results/vespcn/save`
Should work now. Make sure in `datasets.yaml` that **VID4** stands for the original path of VID4 dataset:

>VID4
--original
-----city
--------frame001.png
--------...
-----walk
--------frame001.png
--------...
-----...


Or it can be:
`python eval.py vespcn -t <somewhere>/vid4/input --video --pretrain ../Results/vespcn/save`
