### ISSUE TITLE
Parameter error 

### ISSUE THREAD

**Issue by svb82** [LoSealL/VideoSuperResolution#110]
Hi, I need urgent help. I am training the model drrn on my images , tensorflow backend. When I am trying to train train.py drrn --dataset Data\dataset\images , it's giving me an parameter error .
Error: line 41 drrn.py required two parameters scale and channel.

Appreciate your quick response

**Comment by LoSealL** [comment]
`python train.py drrn --dataset <data-name> --epochs 1000`

I.e.
`python train.py drrn --dataset div2k --epochs 1000`
