### ISSUE TITLE
No information of mcl-v in /Data/datasets.yaml 

### ISSUE THREAD

**Issue by Susan19900316** [LoSealL/VideoSuperResolution#114]
There is no information of mcl-v in /Data/datasets.yaml. Something is wrong when I run "python train.py vespcn --dataset mcl-v --memory_limit 1GB --epochs 100" as guided.

**Comment by LoSealL** [comment]
You can find it here: [http://mcl.usc.edu/mcl-v-database/](http://mcl.usc.edu/mcl-v-database/)

**Comment by kyz20** [comment]
> You can find it here: http://mcl.usc.edu/mcl-v-database/

Could you please tell me how to convert the YUV file to PNG file?

**Comment by LoSealL** [comment]
> > You can find it here: http://mcl.usc.edu/mcl-v-database/
> 
> Could you please tell me how to convert the YUV file to PNG file?

@kyz20 You can refer to [ffmpeg](https://www.ffmpeg.org/)

`ffmpeg -f rawvideo -s 1920x1080 -pix_fmt yuv420p -i <path-to-file.yuv> out_dir/frame_%05d.png`

`-s` follows by the frame width x height, and `-pix_fmt` follows the YUV format. For this MCL-V dataset, it's **yuv420p**. For more information, you can refer to [FOURCC](https://www.fourcc.org/yuv.php)
