### ISSUE TITLE
tecagon model defination vs the pretrained TecoPSNR.pth mismatched keys

### ISSUE THREAD

**Issue by atrah22** [LoSealL/VideoSuperResolution#118]
Hello,
The pretrained TecoPSNR.pth (https://github.com/LoSealL/Model/releases/download/tecogan/tecogan.zip) model mismatches with the model definition in TecoGAN.py. The missing keys while loading the state dict that is,
model.load_state_dict(torch.load(TecoPSNR.pth)) are shown below:

Missing key(s) in state_dict: "gnet.body.0.body.0.weight", "gnet.body.0.body.0.bias", "gnet.body.1.body.0.weight", "gnet.body.1.body.0.bias", "gnet.body.1.body.2.weight", "gnet.body.1.body.2.bias", "gnet.body.17.body.0.1.body.0.weight", "gnet.body.17.body.0.1.body.0.bias", "gnet.body.17.body.1.1.body.0.weight", "gnet.body.17.body.1.1.body.0.bias", "gnet.body.18.body.0.weight", "gnet.body.18.body.0.bias".
       

Unexpected key(s) in state_dict: "gnet.body.19.weight", "gnet.body.19.bias", "gnet.body.0.weight", "gnet.body.0.bias", "gnet.body.17.body.2.weight", "gnet.body.17.body.2.bias", "gnet.body.17.body.0.weight", "gnet.body.17.body.0.bias", "gnet.body.18.body.1.0.weight", "gnet.body.18.body.1.0.bias", "gnet.body.18.body.0.0.weight", "gnet.body.18.body.0.0.bias".

BRs,
Atul

**Comment by LoSealL** [comment]
The training of the tecogan is not finished yet. The weights are not converged. Even though, you can try with the latest code, the unmatched keys shall not block the inference.
While the results are ugly :(
