### ISSUE TITLE
Issue with Vespcn inference questions

### ISSUE THREAD

**Issue by ylz1104** [LoSealL/VideoSuperResolution#12]
When I inference on images, Tensorflow will report a warning:frames is empty[size=-1] .I was used the absolute path .I checked in Loader.py and found that it's happened in _generate_crop_grid method. I don't know why.

**Comment by LoSealL** [comment]
Hi @ylz1104 
Just ignore that warning...
In fact, on inference, I use `size=-1` to indicate that loader will read all the frames in the dataset.

**Comment by ylz1104** [comment]
> Hi @ylz1104
> Just ignore that warning...
> In fact, on inference, I use `size=-1` to indicate that loader will read all the frames in the dataset.

But I have no output sets in results file

**Comment by LoSealL** [comment]
@ylz1104 
What's your evaluation command?

**Comment by ylz1104** [comment]
python run.py --model=vespcn --infer=./data

**Comment by LoSealL** [comment]
@ylz1104 
Please organize your data folder like this:
|data
|--video1
|----frame01.png
|----frame02.png
|----....
|--video2
|----frame01.png
|----frame02.png
|--...

For reference, you can use `python run.py --model=vespcn --test=vid4` or `python run.py --model=vespcn --infer=<absolute-path-to-vid4>/input`

**Comment by ylz1104** [comment]
Thank for you answer ,but still no work

**Comment by LoSealL** [comment]
@ylz1104 
Sounds strange for me. Do you use the default `parameters/vespcn.yaml`? No work for VID4 either?
Could you provide more helpful information?

**Comment by ylz1104** [comment]
I have trained 200 epochs ,and use the GOPRO data.When I train with GOPRO,use python run.py --model=vespcn --dataset=GOPRO --threads=4 --memory_limit=1GB --epochs=200,and the results can reach 28dB.But when I inference ,the above problems have occurred.warnning:frames is empty.[size=-1]    Test: 0it [00:00, ?it/s]. I also confused with it

**Comment by LoSealL** [comment]
@ylz1104 Two questions:
1. can you show the output of 
    ```bash
    ls ./data/*
    ```
2. can you use `--test=vid4` instead of `--infer=./data` first to check out? (If you downloaded vid4 dataset, and manage the corresponding section in `datasets.yaml`)

**Comment by ylz1104** [comment]
1. Thank you for your patience in answering my questions. The problem is solved .I change the VID4 structure according to your method.
2. I want ask another questions about vespcn. Is there a way to adjust the frames size? I didn't find parameters like `--upscale`. 
And what's about vespcn 'real time',It's able to  process 3 frames every seconds on my 1070ti graphics card.

**Comment by ylz1104** [comment]
> @ylz1104
> What do you mean by "adjusting" frame size? If you want another scaling factor (say, x4, x8...), you have to train individual model each. In `vespcn.yaml` you can find a section `scale: 4`, change that value and re-train the model from scratch.
> 
> In my own experiment, the vepscn runtime is 151ms per 180x120x3 clips. (1080)
> Compared to the original paper, here I use more parameters in `Spatial Temporal Network` (3 resblocks), while the author only uses 5 conv layers.
> Second, tensorflow's I/O is not highly optimized for real-time applications, if you read files from disc and write back to disc, the speed may be slow.
> 
> For reference, you can refer to [DUF](https://github.com/yhjo09/VSR-DUF), you can run it directly.

Thanks a lot

**Comment by ylz1104** [comment]
Thanks a lot

**Comment by sunnylulu** [comment]
Hi, 

Is this VESPCN model well-trained? I just found the model consumes more calculation than the original paper, but the result is not so satisfactory.

Thanks

**Comment by ylz1104** [comment]
> Hi,
> 
> Is this VESPCN model well-trained? I just found the model consumes more calculation than the original paper, but the result is not so satisfactory.
> 
> Thanks

The model files with no problem,but the author's IO block has some problems.My suggestion is that you can use Tensorflow data api to deal with datas, the origin program VirtualFile blocks waste too much time and take up too much memory.
I have no idea about origin model well-trained,I was used my own datasets to train.
