### ISSUE TITLE
An error was encountered while running eval

### ISSUE THREAD

**Issue by smoky96** [LoSealL/VideoSuperResolution#120]
Hi,

I have tried the eval.py using
"python eval.py vespcn -t ../Data/vid4/input --pretrain=../Results/vespcn/save"
and get an error:
"SystemError: Parent module 'VSR.Backend.TF' not loaded, cannot perform relative import"
Am I using it the wrong way?

**Comment by LoSealL** [comment]
Maybe you didn't install `VSR` package first?
do
`pip install -e .` 
in the root directory.

**Comment by smoky96** [comment]
> Maybe you didn't install `VSR` package first?
> do
> `pip install -e .`
> in the root directory.

感谢回复！
我安装了 VSR 包。
我对 python 导包的路径一直都弄不太清楚，但我将类似 ```import_module('.Models', 'VSR.Backend.Torch').list_supported_models()``` 的导包语句改为 ```import_module('VSR.Backend.Torch.Models').list_supported_models()``` 后，问题就解决了

**Comment by yfq512** [comment]
@smoky96  请教一下，你是怎么运行的呀？--test 里面是放图片还是视频啊？
