### ISSUE TITLE
Issue with train vespcn on my data.

### ISSUE THREAD

**Issue by AIRedWood** [LoSealL/VideoSuperResolution#15]
1, Good morning， I have some question with train vespcn on my data
 mydata folder like this:
|original
|--video1
|----frame01.png
|----frame02.png
|----....
|--video2
|----frame01.png
|----frame02.png

2, I added parameters in Data/datasets.yaml
MYDATA:
    train: /mnt/data/datasets/mydata/original/
    test: /mnt/data/datasets/vid4/original/
    infer: /mnt/data/datasets/vid4/input/

3, and then ,I input the command: `python run.py --model=vespcn --dataset=MYDATA --threads=4 --memory_limit=1GB`
but is just run on Test and Infer.
INFO:tensorflow:Restoring parameters from ../Results/vespcn/save/vespcn-sc4-ep1000.ckpt
Test: 100%|###########################| 163/163 [00:44<00:00,  4.02it/s]
mse: 301.183258, psnr: 24.019447,
INFO:tensorflow:Inferring vespcn at epoch 1000
Infer: 100%|######################| 163/163 [00:35<00:00,  4.42it/s]

My idea is to train my data and then test it on vid4. What do I need to modify.

**Comment by LoSealL** [comment]
Hi @AIRedWood 
You are tuning on the pre-trained model? Then pass --eposhs=# greater than 1000 `--epochs=2000`.
It will inherit epochs from checkpoint, so will start at 1000, and the default epochs is 50, hence it considers the training is over.
