### ISSUE TITLE
Issue loading some YUV files

### ISSUE THREAD

**Issue by rzumer** [LoSealL/VideoSuperResolution#19]
I have my own data set consisting of raw videos from [xiph.org](https://media.xiph.org/video/derf/), but when trying to use it in VSR I get the following error (line numbers are not up to date because it is my local copy):

```
  File "/home/rzumer/dev/VideoSuperResolution/VSR/DataLoader/Loader.py", line 204, in __init__
    self.prob = self._read_file(dataset)._calc_select_prob()
  File "/home/rzumer/dev/VideoSuperResolution/VSR/DataLoader/Loader.py", line 294, in _calc_select_prob
    weights += [np.prod(f.shape) * f.frames]
  File "/home/rzumer/dev/VideoSuperResolution/VSR/DataLoader/VirtualFile.py", line 379, in shape
    with Image.open(file) as img:
  File "/home/rzumer/dev/tensorflow/lib/python3.6/site-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/project/6006797/rzumer/data/DERF/akiyo_cif.yuv'
```

The files are 8-bit, 4:2:0 and converted from Y4M using ffmpeg.

**Comment by LoSealL** [comment]
Hi @rzumer. What's your [FOURCC](http://fourcc.org/yuv.php) format? Planar or packed?
As you know, I can't handle all YUV formats, and currently, only support YV12/YV21/NV12/NV21 (4:2:0 format). For your simplicity, make a conversion to either of those 4 formats, and specify your data in `datasets.yaml` description file.

For instance, you can refer to MCL-V section in `datasets.yaml`

**Comment by rzumer** [comment]
Thank you for the reminder, I think that my problem was an error in the dataset configuration. Also, the size of my videos are variable, so I will need to change that. Since this is my error I will close this issue.
