### ISSUE TITLE
some Q

### ISSUE THREAD

**Issue by OhniMik** [LoSealL/VideoSuperResolution#2]
May I ask your Environment?
like Ubuntu, Python, tensorflow, tensorflow_gpu, CUDA, CUDNN vesion

**Comment by LoSealL** [comment]
Do you have any problems?
My Env:
========
1. Win10 + PY 365 + tf 1.10 + CUDA 9.0 + cuDNN 7.1
2. Ubuntu 16/18 + PY36 + tf 1.10 + CUDA 9.0 + cuDNN 7.1
