### ISSUE TITLE
Issure with VESPCN

### ISSUE THREAD

**Issue by AIRedWood** [LoSealL/VideoSuperResolution#20]
In VESPCN's paper，the method of multi-frame fusion includes: early fusion、slow fusion and 3D convolution.

I found in the source code that the fusion part only uses early fusion.
 `ef = tf.concat(warps + [input_center], axis=-1)`

So, I want to ask, how to use slow fusion or 3D convolution

**Comment by LoSealL** [comment]
Hi @AIRedWood ,

In the **experiment** section of the paper, they compare single frame (SF), early fusion (E3, E5, E7), and slow fusion (S5, S5 with shared weights). They didn't mention 3D fusion. And as you can tell, early fusion gets the best performance, so I don't implement slow fusion and 3D fusion.

In recent papers, 3D fusion is also known as 3D conv (as far as I can see). You can refer to `VSR-DUF`.

As for your implementation, 3D convolution can be directly applied to 5-dim tensors ([B, T, H, W, C], where T refers to times). I also implement an alias as `Layers.conv3d` in `LayersHelper.py`.
Slow fusion is not very clearly stated in the literature. So I guess it convolves every 2 consecutive frame features, and finally get one fusion feature map.
