### ISSUE TITLE
issue of the result of VESPCN

### ISSUE THREAD

**Issue by AIRedWood** [LoSealL/VideoSuperResolution#22]
Hello, the PSNR of VESPCN is worse than that in the paper. What is the reason?

**Comment by LoSealL** [comment]
Hi @AIRedWood 
There's a related issue #10, please @ me again if anything still unclear.

**Comment by AIRedWood** [comment]
you said in issue10:

PSNR we use to metric the performance is calculated a bit tricky:
In the code of mine, I directly get PSNR on 3 channels (RGB, or just 1 for Y);
But in the research, people do this. First translate RGB image into YUV via the matlab function rgb2ycbcr, and only calculated on its Y channel (luminance channel), in this way the PSNR can increase about 2dB (surprised?)

and  the code in vespcn:
self.metrics['psnr'] = tf.reduce_mean(tf.image.psnr(label_center, sr, 255))


But I don't know how to call rgb2ycbcr. Can I use YUV mode to calculate PSNR in the training code?

**Comment by AIRedWood** [comment]
I run the coomand:
python run.py --mode=eval --input_dir=/VSR/Results/vespcn/MYDATA --test=vid4 --l_only --enable_psnr --enable_ssim

It shows:
    frames += self._process_at_file(file, file.frames)
  File "../VSR/DataLoader/Loader.py", line 353, in _process_at_file
    frames.append(self._vf_gen_custom_pair(vf, depth, i))
  File "../VSR/DataLoader/Loader.py", line 322, in _vf_gen_custom_pair
    frames_lr = [img for img in vf.pair.read_frame(depth)]
  File "../VSR/DataLoader/VirtualFile.py", line 346, in read_frame
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "../VSR/DataLoader/VirtualFile.py", line 346, in <listcomp>
    image_bytes = [BytesIO(self.read()) for _ in range(frames)]
  File "../VSR/DataLoader/VirtualFile.py", line 143, in read
    raise EOFError('End of File!')
EOFError: End of File!

**Comment by LoSealL** [comment]
@AIRedWood Which branch did you use, `master` or `dev` branch?
My test at `master` is OK. 
> python run.py --mode=eval --input_dir=/VSR/Results/vespcn/MYDATA --test=vid4 --l_only --enable_psnr --enable_ssim

Is your `input_dir` right? Since it seems to be an absolute path

**Comment by LoSealL** [comment]
As for `rgb2ycbcr`, the implementation is at `VSR/Util/ImageProcess.py:232`

**Comment by AIRedWood** [comment]
@LoSealL  thank you ， I test it  successfully， the psnr is 25.12.

**Comment by AIRedWood** [comment]
@LoSealL 

But I find a new question.
you said in question 10:
In reference paper, the author's optical flow is ranged from [-1, 1], but interpreted as the entire motion (i.e. a car from coord(0, 0) to coord(W, 0)). But this makes the network very hard to converge. So I constrain the motion to absolutely 1 pixel, which means the estimated movement is at most 1 pixel. A tricky but not mentioned trick at SPMC[2].


I see it in the code.
`def warp(image, u, v, additive_warp=True, normalized=False):
  """warp the image with flow(u, v)
  If flow=[u, v], representing motion from img1 to img2
  then `warp(img2, u, v)->img1~`
  Args:
       image: a 4-D tensor [B, H, W, C], images to warp
       u: horizontal motion vectors of optical flow
       v: vertical motion vectors of optical flow
       additive_warp: a boolean, if False, regard [u, v]
         as destination coordinate rather than motion
         vectors.
       normalized: a boolean, if True, regard [u, v] as
       [-1, 1] and scaled to [-W, W], [-H, H] respectively.`


Could you tell me more about the significance of using normalized?

**Comment by LoSealL** [comment]
@AIRedWood 
If `normalized` is False, then `u` and `v` is the absolute pixel value. For example, u(1, 1)=1 means the motion at (1, 1) on `u` direction (a.k.a **x** direction) is **1**. Here **motion** means **velocity**(or \Delta u) if `additive_warp`=True, or means **destination** (u_{new}) if `additive_warp`=False.

If `normalized` is True, u(1, 1)=1 means the motion at (1, 1) is W, where W is the width of the inputs. And the motion of 1 pixel is 1/W.

**Comment by AIRedWood** [comment]
@LoSealL 
May I ask if I understand this correctly?

If normalized is True, the relative displacement of a pixel is in the interval W* [1,1], that is, [-W, W], and if normalized is False, then the relative displacement of a pixel is [-1,1].

That is to say, normalized enlarges the range of intervals.

**Comment by LoSealL** [comment]
Yes, exactly

**Comment by AIRedWood** [comment]
@LoSealL  thank you~
