### ISSUE TITLE
Issue regarding the input image color space in the VDSR network 

### ISSUE THREAD

**Issue by leptdre** [LoSealL/VideoSuperResolution#3]
As far as I know, VDSR upscale only the Y channel through the network, however, I could not see that in your code. Could you please confirm if it is performed or not ? 

See this tutorial: 
https://www.mathworks.com/help/images/single-image-super-resolution-using-deep-learning.html

**Comment by LoSealL** [comment]
You can set --channel (in version <=0.4), or `channel` section in yaml config file (the latest version).
If you'd like the original VDSR, channel is 1, or you can train with RGB channels.

P.S It's the same with SRCNN and ESPCN, who originally trained only with luminance channel.
