### ISSUE TITLE
After trained VESPCN in tensorflow , why the shape changed? not exactly x4?

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#32]
I trained VESPCN in tensorflow with `scale=4` , and lr shape is 480x270, hr is 1920x1920. But when I use `CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --infer /nfs/hym/tf_estimator_barabone-master/data/VIDEO_BEA/test_LR_x4_noisy2/` 
The result shape is 1920*1088. Why ?  
![image](https://user-images.githubusercontent.com/26487821/56331645-cd265500-61bf-11e9-8416-f3b70c313dea.png)

**Comment by HymEric** [comment]
And another question.
I use CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --test=video_bea_test_x4_n2 to try. Ange get this, it can get PSNR but the result still is 1920x1088 instead of 1920x1080.....
It is amazing the performance in this order is much better than above order. Why?

![C@Y@IG9XE3HCKJZDXU)TE4H](https://user-images.githubusercontent.com/26487821/56331468-014d4600-61bf-11e9-97cc-8c5b4f758622.png)

**Comment by LoSealL** [comment]
@HymEric Check the design of `SPMC`, motion compensation network in `VESPCN`. In corse flow estimation, the input LR-space features are strided by 4, therefore as an input of height 270, I pad it to 272 to make it divided by 4. And the final output should be 272*4=1088

**Comment by HymEric** [comment]
OK. But why the result is different in different order to infer?
`CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --infer /nfs/hym/tf_estimator_barabone-master/data/VIDEO_BEA/test_LR_x4_noisy2/`

`CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --test=video_bea_test_x4_n2`

See detail above pictures.

**Comment by LoSealL** [comment]
@HymEric What did you mean by `order`? What's the difference exactly, i.e. the PSNR value? Could be the misalignment between predicted frames and labels?

**Comment by HymEric** [comment]
I mean that different order line produce different results by same trained model vespcn. You can see the second picture is better than the first. And first is produced by `CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --infer /nfs/hym/tf_estimator_barabone-master/data/VIDEO_BEA/test_LR_x4_noisy2/`
And second is produced by `CUDA_VISIBLE_DEVICES=1 python run.py --model vespcn --test=video_bea_test_x4_n2`

**Comment by LoSealL** [comment]
How do you get `test_LR_x4_noisy2` frames? It seems more than just bicubically downsample from HR.

_P.S._ The difference between `--infer` and `--test` is that `--infer` directly predict on given inputs, while `--test` resample the given inputs to the target LR and calculate metrics to the original inputs. But I thought this is not the key to your issue.

**Comment by HymEric** [comment]
I use pair dataset in datasets.yaml
```
 VIDEO_BEA_TEST_X4_N2: 
    test: ['VIDEO_BEA/test_HR_beauty/']
    test_pair: ['VIDEO_BEA/test_LR_x4_noisy2/']
```
--test bot use the test_pair???

**Comment by LoSealL** [comment]
Oh, it does use the pair. I forgot your case.

**Comment by HymEric** [comment]
I know why. I forget to add
```
param:
      parser: custom_pairs
```
So, when I use --test, it really use the target HR to produce LR. But --infer use my hand-crafted LR image. This is the reason why the result is different.

And when I use
```
 VIDEO_BEA_TEST_X4_N2: 
    test: ['VIDEO_BEA/test_HR_beauty/']
    test_pair: ['VIDEO_BEA/test_LR_x4_noisy2/']
    param:
      parser: custom_pairs 
```
It show
```
frames is empty. [size=-1]
Test: 0it [00:00, ?it/s]

frames is empty. [size=-1]
```
Seems custom_pairs  is not work.

**Comment by LoSealL** [comment]
@HymEric Yeah, I just busy reproducing on VID4 and found an error in `custom_pairs.py`.

For a quick test, add `vf.pair.pad([depth // 2, depth // 2])` after line 59.
Still, my fault, forget to configure paired files.
