### ISSUE TITLE
Why vespcn is not better than EDSR in same training datasets?

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#35]
Why vespcn is not better than EDSR in same train datasets? 
Any advice to get higher PSNR and SSIM?

**Comment by LoSealL** [comment]
Many reasons, so I am not able to explain details here. Be aware that maximum pixel displacement (the max output of optical flow) in Tensorflow's VESPCN is only **1** in my implementation. 
Now I suggest following the PyTorch's implementation and extend the max displacement to around **32**.

BTW, EDSR has much more parameters than VESPCN here.

**Comment by HymEric** [comment]
Thank you.
