### ISSUE TITLE
how to train motion compensation and SR model separately and then joint train in VESPCN according to paper?

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#38]
how to train motion compensation and SR model separately and then joint train in VESPCN according to paper?

**Comment by LoSealL** [comment]
Briefly, you just need to control how `build_graph` in the different training phase. Specifically, use different loss in `build_loss` to optimize.

## VSR
For example, the total loss is `L=Lf + Ls` where Lf is the flow loss and Ls is the image loss.
Use an optimizer and pass the trainable variables just collect from your `Fnet` to optimize flow loss only.
Second, it's the same to use another optimizer to optimize image loss only. Finally, use a third optimizer to optimize the total loss.

If you want to save different sub-network separately. See `build_saver` for details.

## VSRTorch
It's the same, while I think it's easier to write code under torch.

**Comment by HymEric** [comment]
I get it. Thank you.
