### ISSUE TITLE
Issue with python version and empty data folder

### ISSUE THREAD

**Issue by mirkocoric** [LoSealL/VideoSuperResolution#4]
Thank you very much for sharing this scripts!
I am writing this to inform you about two issues which I encountered when trying to learn models with train.py (everything works in python 3.6 and right data folder, but warnings might be helpful for future users):
1. When using python version 3.5.1 the following error appears:
File "Train/train.py", line 62 
 if Path(f'parameters/{args.name}.json').exists()
 SyntaxError: invalid syntax
2. When data folder is empty (which causes len(frames) = 0):
...
File "/Users/mirkocoric/Documents/vde/super-resolution/VideoSuperResolution/VSR/DataLoader/Loader.py", line 534, in _generate_crop_grid
index = np.random.randint(len(frames), size=size).tolist()
 File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by LoSealL** [comment]
Hi @mirkocoric 
#### 1st Q:
With python syntax: `f'string-{var}'`, this string format syntax only works after python 3.6, however, it's the same as `'string-{}'.format(var)`.

#### 2nd Q:
Yeah, that's a bug for empty dataset (especially triggered in training). I fixed it in today's commit.
Thank you :)
