### ISSUE TITLE
TecoGAN support

### ISSUE THREAD

**Issue by rzumer** [LoSealL/VideoSuperResolution#41]
I would like to use this issue to track TecoGAN integration specifically. I don't want to apply pressure, but I am particularly interested in using the implementation for this model. If I can help at all (e.g. with testing the implementation), please let me know how I can contribute.

I see that there is a preliminary Torch implementation in the `dev` branch already. I would like to clarify the current status:
- What has and has not yet been implemented/tested?
- Can you provide any estimate timeline for the remaining work?

**Comment by LoSealL** [comment]
Thanks for your interests! Currently, I am testing VGG and GAN loss function with srgan and esrgan, and then:
- Training PSNR version with Ping-pong loss for TecoGAN
- Transfer official pretrained weights to VSRTorch's version
- Fully training TecoGAN (L2 + Ping-ping + VGG + GAN + GAN-VGG)

The difficulty may lie in:
- Balancing weights among loss terms
- Searching for proper learning rate and how it decays.
- Others?

**Comment by rzumer** [comment]
Thank you for the information. If I understand correctly the remaining work is mostly for adding the pre-trained model. Is it possible to test training the network now? Adding TecoGAN to the list of supported VSRTorch models works, but `dnet` initialization fails with the error "optimizer got an empty parameter list" (and if setting `self.dopts` = `self.gopts`, further down the line I get `TypeError: forward() takes 4 positional arguments but 5 were given`).

**Comment by LoSealL** [comment]
Of course not. Training GAN-oriented model requires a lot to do. The discriminator has not been committed yet, while I'm now training the PSNR-oriented model for the initialization.

Transferring per-trained weights could help us better understand and verify the training procedure.

**Comment by LoSealL** [comment]
The training is now enabled, (but not fully tested), transferred weights will be uploaded soon. @rzumer

**Comment by rzumer** [comment]
Thank you very much.

**Comment by rzumer** [comment]
I tested training from scratch based on the latest dev branch revision, on two different systems (with and without CUDA on one of them) but keep running out of memory (the process eventually gets killed via `oom-kill` event). This happens before training the first epoch usually, though on one system (with `--scale 2`) I managed to train one epoch before the process was killed. The same issue occurs with FRVSR, while other models I tested work as expected.

I have 12GB GPU memory and 32GB RAM on the higher end system on which I tested.

I tried reducing the parameters down to 4 batches of size 32 with no success, and have not yet tried going lower. I would also like to ask what hardware and dataset is used for testing on your end, so that I can try to reproduce your setup if possible.

**Comment by LoSealL** [comment]
Use `--memory_limit=8GB` to limit to a reasonable value. The dataloader may load duplicated frames (time strides 1) so memory overhead is quite large.

For example:
X{0,1,2,3,4,5} will be loaded as (given `depth=3`) X[0,1,2], X[1,2,3], X[2,3,4], X[3,4,5].

Another option is to use HDF5 binary format. See VIMEO dataset for reference.

**Comment by rzumer** [comment]
Unfortunately setting `--memory_limit` does not seem to be enough, even without `--cuda`. I will look into the HDF5 format and update. If you would like I can create a new issue regarding this problem. Also, it may be helpful to add information on the various ways to reduce memory usage in the readme.

**Comment by LoSealL** [comment]
You could add `-v` and send me some log. I will check if this relates to a bug,

**Comment by rzumer** [comment]
Here is sample verbose output for a job running on a high performance node of the Cedar cluster of Compute Canada (requested with 32GB RAM, GPU should be NVIDIA P100 Pascal (12G HBM2 memory)).

I have abridged the log to only show the last 20 lines of prefetching and final error, since there hundreds or thousands of lines of prefetching logging. I can provide more if needed. Note: while this log is from a run using `--scale 1`, using my fork of VSR (`personal` branch), please note I have tested multiple configurations, including with `--scale 2` which is not affected at all by my changes, and the point of failure is the same for all of them.

I attempted to reduce the size of the dataset by deleting some clips in case too many were being prefetched. My latest test includes only 5 training clips and 8 validation clips. The clips are all in CIF resolution and are sourced from [this page](https://media.xiph.org/video/derf/). It is possible that there are many more frames than the usual datasets and due to the eager loading (prefetching) of the frames, it amounts to an excessive amount even for systems with high memory capacity.

I will test some more with fewer clips and with one of the datasets suggested in the README, and will update if I manage to find a working configuration.

```
2019-05-16 13:11:24,095 DEBUG: Prefetching silent_cif @38
2019-05-16 13:11:24,119 DEBUG: Prefetching bridge_close_cif @1749
2019-05-16 13:11:24,167 DEBUG: Prefetching waterfall_cif @164
2019-05-16 13:11:24,185 DEBUG: Prefetching bridge_close_cif @1960
2019-05-16 13:11:24,278 DEBUG: Prefetching akiyo_cif @39
2019-05-16 13:11:24,292 DEBUG: Prefetching bridge_close_cif @750
2019-05-16 13:11:24,367 DEBUG: Prefetching bridge_close_cif @150
2019-05-16 13:11:24,371 DEBUG: Prefetching akiyo_cif @282
2019-05-16 13:11:24,394 DEBUG: Prefetching silent_cif @224
2019-05-16 13:11:24,407 DEBUG: Prefetching hall_monitor_cif @53
2019-05-16 13:11:24,463 DEBUG: Prefetching bridge_close_cif @648
2019-05-16 13:11:24,478 DEBUG: Prefetching football_cif @117
2019-05-16 13:11:24,557 DEBUG: Prefetching waterfall_cif @221
2019-05-16 13:11:24,583 DEBUG: Prefetching bridge_close_cif @1013
2019-05-16 13:11:24,649 DEBUG: Prefetching bridge_close_cif @1316
2019-05-16 13:11:24,661 DEBUG: Prefetching silent_cif @97
2019-05-16 13:11:24,667 DEBUG: Prefetching bridge_close_cif @331
2019-05-16 13:11:24,708 DEBUG: Prefetching bridge_close_cif @1276
2019-05-16 13:11:24,741 DEBUG: Prefetching silent_cif @60
2019-05-16 13:11:24,785 DEBUG: Prefetching football_cif @223
/var/spool/slurmd/job21104355/slurm_script: line 12: 156391 Killed                  python train.py tecogan -v --cuda --scale 1 --epochs 100 --dataset DERF
```

**Comment by LoSealL** [comment]
Please notice initialization logs in `Loader.py`, for example, memory capacity and available memory.
Also, do you notice any exception in fetching thread?

**Comment by LoSealL** [comment]
Check if the system avaiable memory and estimated data capacity are reasonable. Sometimes, data capacity could be overflow (i.e. use `int32` type rather than `uint64` by mistake)

**Comment by rzumer** [comment]
Sorry, I made a mistake while looking at my latest log. After reducing the number of training clips the training was actually able to run for one epoch. I believe that after reducing the number of validation clips as well, it will likely be able to run a validation pass and hopefully the rest of the training as well (in the log posted above, the process was killed during the first validation pass).

I have a new job queued to test this hypothesis and will provide an update once I have more information.

Hardware information does not seem to be included in my log, possibly because only stdout or stderr but not both is redirected to file. I will look into this as well.

**Comment by rzumer** [comment]
I can confirm that training is running correctly when training + validation sets are sufficiently small. I underestimated the requirements for my dataset. Sorry for the confusion.

**Comment by HymEric** [comment]
I have a question. Is hard to train TecoGan in the package?  As we know, GAN is hard to train and in generally.

**Comment by rzumer** [comment]
I tried test/inference with the model but can't seem to get it working, is it unimplemented or is my syntax wrong?

`python train.py tecogan --cuda --scale 1 --epochs 100 --[test/infer] <my_dataset>`

Where `<my_dataset>` is defined with `test` and `infer` paths, parameters, etc. as usual.

Output is as follows:
```
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main()
  File "train.py", line 85, in main
    suppress_opt_by_args(model_params, *args)
  File "/home/rzumer/dev/VideoLowLevelVision/VSR/Tools/Run.py", line 220, in suppress_opt_by_args
    raise KeyError("Parameter {} doesn't exist in model!".format(key))
KeyError: "Parameter [test/infer] doesn't exist in model!"
```

**Comment by LoSealL** [comment]
`python train.py tecogan --cuda --scale 1 --epochs 100 --test <my_dataset>`

Why are you using `scale=1`?

**Comment by rzumer** [comment]
Sorry, deleted my comment as I noticed I was running `train.py` instead of `eval.py`.

I use `--scale 1` with some changes to train for non-SR applications on images with equal size (e.g. image quality enhancement).

**Comment by rzumer** [comment]
For the record, at `--scale 1` this model does not work well at all. There is ghosting, texture disappearing and reappearing, and other odd artifacts showing up in the output. This is based on 100-epoch training, for artifact reduction.

**Comment by LoSealL** [comment]
Yes, I'm aware of that. Mainly because of `Util.Utility.upsamle(downsample)` where scale!=2^n causes troubles.

**Comment by rzumer** [comment]
I have not tested much, but if this were an issue with the `upsample()` function, wouldn't it affect all models? I have trained FRVSR, SRGAN, VESPCN and other models successfully, but TecoGAN alone gives very low quality output on inference.

I have tested training for another 100 epochs and noticed that the validation set (which is a subset of the training set, natural videos with the same resolution) converges to a fairly high PSNR value. However on inference I am using the Vid4 set. The resolution is different and the output quality is terrible. I am wondering if this may have something to do with the resolution.

I will later test inference on cropped Vid4 clips, to reduce them to the same resolution as the training set, and see if this changes the result.

**Comment by LoSealL** [comment]
@rzumer The `upsample()` I mentioned (*notice: lower case*) is a constant interpolation function, you can regard it as a bicubic interpolator. This `upsample` is only used in where needs upscale LR to HR-space first.

Another `Upsample` (*notice: upper case*) is a module that applied in every SR model, it's a trainable layer.

And in detail, `FRVSR`, `SRGAN`, or `VESPCN` don't use `upsample` with `scale=1` so the bug didn't affect them.
In the last commit, I have already fixed the problem of `upsample` and bypass the data when `scale=1`

Furthermore, you can share a PTH checkpoint and YML file and I could help you diagnose the issue.

**Comment by rzumer** [comment]
I tried disabling the function call in my last training attempt last week, but it is possible that I missed something. I will try rebasing and retraining. Thank you for the details.

**Comment by rzumer** [comment]
Sorry for the delay. I have rebased and retested training and inference from scratch and I believe it now works as expected. Thank you for your help.

**Comment by rzumer** [comment]
Please feel free to reopen if needed, as I see the network is still marked as in testing.
