### ISSUE TITLE
How to test images on different scales?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [LoSealL/VideoSuperResolution#45]
As the title, how can I use pre-train model to infer image with different scales?

**Comment by LoSealL** [comment]
For most models, you need to re-train them. If your request is not very accurate, you may rescale the up-sampled outputs using bicubic filters.

>>> X2 = X4 -> Bicubic(1/2)
>>> X3 = X4 -> Bicubic(3/4)

**Comment by LoSealL** [comment]
For CARN, MDSR, the pre-trained model is X2/X3/X4.
For example CARN (torch's version), you can upscale by a factor of 2/3/4:
```shell
# Download carn.pth and carn_m.pth
python prepare_data.py --filter Tcarn
cd VSRTorch
python eval.py carn --cuda --multi_scale 1 --scale 2 -t set5 --pth ../Results/carn.pth
python eval.py carn --cuda --multi_scale 1 --scale 3 -t set5 --pth ../Results/carn.pth
python eval.py carn --cuda --multi_scale 1 --scale 4 -t set5 --pth ../Results/carn.pth
```
