### ISSUE TITLE
why multiply self.body(x) with self.gain=32 in FNet?

### ISSUE THREAD

**Issue by xyfZzz** [LoSealL/VideoSuperResolution#46]
In VSRTorch/models/frvsr/ops.py, why multiply self.body(x) with self.gain=32 in FNet? What self.gain means?

**Comment by LoSealL** [comment]
In the last layer, there's a `Tanh` activation to normalize the output to [-1, 1], representing the relative movement. The `gain` represents the absolute pixel movement, meaning the optical flow is constrained to [-gain, gain].

This helps convergence for **unsupervised** flow estimation.

**Comment by xyfZzz** [comment]
> In the last layer, there's a `Tanh` activation to normalize the output to [-1, 1], representing the relative movement. The `gain` represents the absolute pixel movement, meaning the optical flow is constrained to [-gain, gain].
> 
> This helps convergence for **unsupervised** flow estimation.

But I see the flow pass to the STN in VSRTorch/models/video/motion.py was normalized by `_u = u / w * 2` and `_v = v / h * 2`,  it seems that the flow does not  been normalized to [-1, 1]. Will it make any bug?

**Comment by xyfZzz** [comment]
> No, that's what you must do when applying `grid_sample` of Torch. See torch's doc for details.

Yes, I have  seen the doc of `grid_sample`, the arg `grid` has values in the range of `[-1, 1]`. But I means if flow has the range of `[-gain, gain]` which `gain` is `32`, then using `_u = u / w * 2` and _`v = v / h * 2 `when `w=16` and `h=16`, will it makes the flow's range be `[-4, 4]`?

**Comment by LoSealL** [comment]
if `w=16`, and `gain>=16`, which means the movement is beyond the entire picture. In that case, `sample_grid` will overflow. In practice, it will sample border pixel or zero pixel according to your padding mode.

**Comment by LoSealL** [comment]
BTW, `*2` is a normalization step because the range is `[-1, 1]`.

**Comment by xyfZzz** [comment]
> BTW, `*2` is a normalization step because the range is `[-1, 1]`. `_u = u / ( w / 2)`

Thanks. So, I see in the code, the `gain` is set to a value of `32`, while the values of `w`  and `h` is according to the input image's size, will it make a projection error when using `sample_grid`? Or the network will be trained to make the `grid`'value be in the range of `[-1, 1]`?

**Comment by LoSealL** [comment]
The network is trained to predict **absolute** motion value, and this value is limited to [-gain, gain]. Hence change the size of input images doesn't affect the behavior of the network. The **relative** value is just the requirement for calling torch's `sample_grid`.
