### ISSUE TITLE
SPMC

### ISSUE THREAD

**Issue by musicrainie** [LoSealL/VideoSuperResolution#47]
Looking forward to your SPMC implementation.

**Comment by LoSealL** [comment]
Which framework will you prefer? TF or Torch?

**Comment by musicrainie** [comment]
I prefer PyTorch, which is more friendly to people like me.
Thanks for your instant reply.

**Comment by LoSealL** [comment]
SPMC was added in VSRTorch, you can checkout as `dev` to help me verify it :)
