### ISSUE TITLE
datasets.yaml

### ISSUE THREAD

**Issue by Confusedisprecious** [LoSealL/VideoSuperResolution#48]
what the 'Path' and 'Path_Tracked' mean?  where are the 'train_input' and 'train_label'

**Comment by LoSealL** [comment]
They are briefly introduced in README file in their subfolders.

It's recommended to read them first. Any question furthur, I am pleased to answer them later.

**Comment by Confusedisprecious** [comment]
> They are briefly introduced in README file in their subfolders.
> 
> It's recommended to read them first. Any question furthur, I am pleased to answer them later.

The command of training VDSR is given  in README is as follows:
` Python run.py -- model VDSR -- epochs 100 -- dataset 91 - Image -- Test none -- infer. / test. png`
In datasets, the 91 - Image dataset is defined as follows:
  91-IMAGE:  # Yang's 91 images
    train: 91-IMAGE
    val: [SET5]
    test: [SET5, SET14]
 Path:
91-IMAGE: 91-image/
However, I found that the 91-Image image is like this:
T1.bmp
...
T66.bmp
Tt1.bmp
...
Tt27.bmp
What I want to understand is how train_input (low resolution images) and train_label (high resolution images) are distinguished under the 91-Image folder. I didn't see the path to the train_input and training_label in datasets. yaml. I looked at the code and still couldn't figure it out.
If I want to train my data set.
the data the folders have the structure:
1_lr:
001_lr.png
002_lr.png
:
100_lr.png
2_lr:
001_lr.png
002_lr.png
:
100_lr.png
1_hr:
001_lr.png
002_lr.png
:
100_lr.png
2_lr:
001_lr.png
002_lr.png
:
100_lr.png
1_lr and 1_hr are train_input (low resolution images) and train_label (high resolution images) of a set of video sequences. The same is true for 2_lr and 2_hr.

**Comment by LoSealL** [comment]
It comes to the concept of `parser`. You can check under `VSR/DataLoader/Parser`.
The YAML config file tells how to glob files into loaders, while `parser` tells how to pre-process and divide files. 

For globing, it will search patterns just like `Path.glob`, the search depth is 0 or 1:
- If you want to search single files, use `/path/somewhere/**/*.png` for recursively searching or `/path/somewhere/*.bmp` for shallow searching. 
- If you want to search video sequence files, use `/path/video/parent/dir`.

For parser, by default we use `default_parser`, it globs files and regards them as ground-truth. It uses PIL's resize to downsample to LR images while pre-loading them on the air.

If you have a customized HR-LR pair, you can use `custom_pairs`. See the examples of `SIDD` or `VIDEOPAIR` in `UTest/data/fake_datasets.yml`:
```yaml
YOURDATA:
  train: "/a/b/c/*_hr"
  train_pair: "/a/b/c/*_lr"
  param:
    parser: custom_pairs
```

**Comment by Confusedisprecious** [comment]
> It comes to the concept of `parser`. You can check under `VSR/DataLoader/Parser`.
> The YAML config file tells how to glob files into loaders, while `parser` tells how to pre-process and divide files.
> 
> For globing, it will search patterns just like `Path.glob`, the search depth is 0 or 1:
> 
> * If you want to search single files, use `/path/somewhere/**/*.png` for recursively searching or `/path/somewhere/*.bmp` for shallow searching.
> * If you want to search video sequence files, use `/path/video/parent/dir`.
> 
> For parser, by default we use `default_parser`, it globs files and regards them as ground-truth. It uses PIL's resize to downsample to LR images while pre-loading them on the air.
> 
> If you have a customized HR-LR pair, you can use `custom_pairs`. See the examples of `SIDD` or `VIDEOPAIR` in `UTest/data/fake_datasets.yml`:
> 
> ```yaml
> YOURDATA:
>   train: "/a/b/c/*_hr"
>   train_pair: "/a/b/c/*_lr"
>   param:
>     parser: custom_pairs
> ```
Thank you very much. Now you can train vespcn. But I also have a question about how I set it up in fake_datasets.y.
Train: "video/train/hr"
Train_pair: "video/train/lr"
Val: "Video/val/hr"
Val_pair: "video/val/lr"
Test: "video/test/hr"
Test_pair: "video/test/lr"
Param:
Parser: custom_pairs
The data folder is structured as follows:
Video:
Train:
---------hr:
-------1:
001.png
:
100.png
-------2:
001.png
:
100.png
:
-----50:
001.png
:
100.png
---------lr:
-------1:
001.png
:
100.png
-------2:
001.png
:
100.png
:
-----50:
001.png
:
100.png
Each video corresponds to 100 image sequences. The subfolders with the same number under HR and LR under the same folder correspond to the high-resolution and low-resolution video of the same video. Val and test have the same file structure. What I want to ask is what's the difference between your framework definition Val and test? My current understanding is one for the training process, one for the completion of training?
There are 50 image sequences (50 videos) in my test folder. Why is there only one image sequence in the results folder after training? Are all the videos in the trian folder used for training? How to modify these parameters?

**Comment by LoSealL** [comment]
Yes, the `val` is used during training, and `test` is used for testing and inferring. The major difference are **batch** and **patch_size**.

It should generate 50 video results, give me more information about it.

The detail of how to generate patches from image files is in `parser`. You can refer to any existing parser and modify as your own requirement.

**Comment by Confusedisprecious** [comment]
Why is the output shape size [1920,1088] rather than [1920,1080], related to path_size?

**Comment by Confusedisprecious** [comment]
> Yes, the `val` is used during training, and `test` is used for testing and inferring. The major difference are **batch** and **patch_size**.
> 
> It should generate 50 video results, give me more information about it.
> 
> The detail of how to generate patches from image files is in `parser`. You can refer to any existing parser and modify as your own requirement.
Why is the output shape size [1920,1088] rather than [1920,1080], related to path_size?

**Comment by LoSealL** [comment]
#32 
> Check the design of `SPMC`, motion compensation network in `VESPCN`. In corse flow estimation, the input LR-space features are strided by 4, therefore as an input of height 270, I pad it to 272 to make it divided by 4. And the final output should be 272*4=1088

**Comment by Confusedisprecious** [comment]
> Check the design of `SPMC`, motion compensation network in `VESPCN`. In corse flow estimation, the input LR-space features are strided by 4, therefore as an input of height 270, I pad it to 272 to make it divided by 4. And the final output should be 272*4=1088


Thank you very much.

**Comment by Confusedisprecious** [comment]
> > Check the design of `SPMC`, motion compensation network in `VESPCN`. In corse flow estimation, the input LR-space features are strided by 4, therefore as an input of height 270, I pad it to 272 to make it divided by 4. And the final output should be 272*4=1088
> 
> Thank you very much.
--Memory_limit means GPU memory?

**Comment by LoSealL** [comment]
`--memory_limit` constrains CPU memory.

**Comment by Confusedisprecious** [comment]
When I used Vespcn (pytorch) for training, there was no problem. However, the following mistakes occurred in infer:
``2019-05-31 15:01:18,558 INFO: Restoring params for vespcn from E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\Results\vespcn\save\vespcn_ep0164.pth.
2019-05-31 15:01:21,059 INFO: Inferring [vespcn] at epoch 164
Infer:   0%|                                                                                   | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "eval.py", line 140, in <module>
    main()
  File "eval.py", line 136, in main
    t.infer(loader, loader_config)
  File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Framework\Trainer.py", line 225, in infer
    self.fn_infer_each_step(None, feature, name)
  File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Framework\Trainer.py", line 248, in fn_infer_each_step
    outputs, _ = self.model.eval([feature])
  File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\Vespcn.py", line 52, in eval
    sr, warps, flows = self.vespcn(*frames)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\vespcn\ops.py", line 100, in forward
    warp, flow = self.mc(target, r)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\vespcn\ops.py", line 60, in forward
    w0 = self.warp1(ref, flow0[:, 0], flow0[:, 1], False)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\video\motion.py", line 37, in forward
    assert flow.shape == mesh.shape
AssertionError

**Comment by Confusedisprecious** [comment]
> `--memory_limit` constrains CPU memory.
> Loading partial data into memory when total size of dataset >= min(memory_limit, free mem)
When I used Vespcn (pytorch) for training, there was no problem. However, the following mistakes occurred in infer:
``2019-05-31 15:01:18,558 INFO: Restoring params for vespcn from E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\Results\vespcn\save\vespcn_ep0164.pth.
2019-05-31 15:01:21,059 INFO: Inferring [vespcn] at epoch 164
Infer: 0%| | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
File "eval.py", line 140, in 
main()
File "eval.py", line 136, in main
t.infer(loader, loader_config)
File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Framework\Trainer.py", line 225, in infer
self.fn_infer_each_step(None, feature, name)
File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Framework\Trainer.py", line 248, in fn_infer_each_step
outputs, _ = self.model.eval([feature])
File "\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\Vespcn.py", line 52, in eval
sr, warps, flows = self.vespcn(*frames)
File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\vespcn\ops.py", line 100, in forward
warp, flow = self.mc(target, r)
File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\vespcn\ops.py", line 60, in forward
w0 = self.warp1(ref, flow0[:, 0], flow0[:, 1], False)
File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSRTorch\Models\video\motion.py", line 37, in forward
assert flow.shape == mesh.shape
AssertionError

**Comment by LoSealL** [comment]
Seems a bug that padding not working.
Make a quick fix at `dev`

**Comment by Confusedisprecious** [comment]
> Seems a bug that padding not working.
> Make a quick fix at `dev`
Has pytorch been upgraded to version 1.1.0?
There is no torch. repeat_interleave in version 1.0.1

**Comment by LoSealL** [comment]
Yes, I upgraded to 1.1.0

**Comment by Confusedisprecious** [comment]
This problem arose when I went to infer after my upgrade:
OSError: [Errno 24] Too many open files:
How can I fix  to infer more images  at once?

**Comment by Confusedisprecious** [comment]
> Yes, I upgraded to 1.1.0

This problem arose when I went to infer after my upgrade:
OSError: [Errno 24] Too many open files:
How can I fix to infer more images at once?

**Comment by LoSealL** [comment]
Edit /etc/security/limits.conf adding
> * soft nofile 8192
> * hard nofile 8192

**Comment by LoSealL** [comment]
8192 can be more like 65535

https://www.robustperception.io/dealing-with-too-many-open-files

**Comment by RuyiLuo** [comment]
I encounter a problem When I add my own data to train models.
First, if the data form as follow,  
```
MYDATA:    
  train: "y_train_data/*.bmp"   
  train_pair: "x_train_data/*.bmp"    
  val: "y_valid_data/*.bmp"     
  val_pair: "x_valid_data/*.bmp"    
  param:    
      parser: custom_pairs
```


when I run code , there is  no any issue.

However, when I set the data form as follow,
```
MYDATA:  
    train: "y_train_data/*.bmp"
    train_pair: "x_train_data/*.bmp"
    val: "y_valid_data/*.bmp"
    val_pair: "x_valid_data/*.bmp"
    infer: ["x_test_data"]
    # infer: "x_test_data/*.bmp"
    # infer: ["x_test_data/"]
    param:
        parser: custom_pairs
```

The traceback as follow shows:

```
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    tf.app.run(main)
  File "/home/ryluo/anaconda3/envs/tf12/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run.py", line 42, in main
    return Run.run(*args[0][1:], **additional_functions)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/Tools/Run.py", line 320, in run
    infer_loader = loader(infer_data, 'infer', infer_config)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 322, in __init__
    augmentation, **kwargs)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 127, in __init__
    self.parser = _m.Parser(dataset, config)
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 24, in __init__
    assert len(urls) == len(pair)
AssertionError
```

**AssertionError!**

How to correctly set the data form with "infer" section in datasets.yaml.

Thanks.
ruyi.

**Comment by LoSealL** [comment]
I think it's better to use `run.py --infer xxx`, where `xxx` can be an URL or a binding name in `Path_Tracked`

**Comment by LoSealL** [comment]
Leaving `infer` with `custom_paris` parser does make errors above.

**Comment by Confusedisprecious** [comment]
> 8192 can be more like 65535
> 
> https://www.robustperception.io/dealing-with-too-many-open-files
I encountered this problem on Windows 10 platform:
OSError: [Errno 24] Too many open files:
Previous project versions were working. I evaluated 5,000 images at a time.

**Comment by LoSealL** [comment]
Ok, I will evaluate on Windows. The parser will open 5000*2 fd (file descriptions) to make indexes.

**Comment by Confusedisprecious** [comment]
> Ok, I will evaluate on Windows. The parser will open 5000*2 fd (file descriptions) to make indexes.
thank you

**Comment by Confusedisprecious** [comment]
> Ok, I will evaluate on Windows. The parser will open 5000*2 fd (file descriptions) to make indexes.

In .. \VideoSuperResolution \master\ VSR DataLoader\ VirtualFile.py
The current version uses the following:
LR = [img for img in vf. pair. read_frame 2 (depth)]
Previous versions are:
LR = [img for img in vf. pair. read_frame (depth)]
"read_frame 2" will report errors when infer images are large.

**Comment by LoSealL** [comment]
Can you solve this by just eliminating `2`?

**Comment by LoSealL** [comment]
@Confusedisprecious Add a new loader for this. Use `dev` branch, and set an environment:
- linux: `export VSR_SEQ_LOADER=1`
- win10: `set VSR_SEQ_LOADER=1`

Then run as usual.

**Comment by Confusedisprecious** [comment]
> `dev` branch

Don't understand how to modify it?

**Comment by LoSealL** [comment]
`git checkout dev`

**Comment by Confusedisprecious** [comment]
> `git checkout dev`
After I updated to dev branch, I still couldn't work.
The following mistakes still occurred：
`Exception in thread fetch_thread_7:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
  File "D:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSR\DataLoader\Loader.py", line 257, in _prefetch
  File "E:\VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSR\DataLoader\Parser\custom_pairs.py", line 65, in __getitem__
  File "E:VSRIntegration\VideoSuperResolution-master\VideoSuperResolution-master\VSR\DataLoader\Parser\custom_pairs.py", line 86, in gen_frames
  File "E:VideoSuperResolution-master\VideoSuperResolution-master\VSR\DataLoader\VirtualFile.py", line 374, in read_frame2
OSError: [Errno 24] Too many open files: 'E:\\data\\infer\\249\\00245\\047.png'`

**Comment by LoSealL** [comment]
Do you set the environment?

**Comment by RuyiLuo** [comment]
I  have cloned dev branch to train SISR model, and I also set the environment that edit /etc/security/limits.conf adding and export VSR_SEQ_LOADER=1,
but I have the same traceback:

```
Traceback (most recent call last):
  File "/home/ryluo/anaconda3/envs/VSR/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/home/ryluo/anaconda3/envs/VSR/lib/python3.6/threading.py", line 864, in run
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Loader.py", line 271, in _prefetch
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 70, in __getitem__
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/Parser/custom_pairs.py", line 86, in gen_frames
  File "/home/ryluo/Desktop/VideoSuperResolution-master/VSR/DataLoader/VirtualFile.py", line 369, in read_frame2
OSError: [Errno 24] Too many open files: '/home/Datasets/mydata/2289.bmp' 
```

**Comment by LoSealL** [comment]
@RuyiLuo 
You are in `:line 271` of `Loader`, most likely the free memory is not enough for loading all files.
There is another bypass environment:
`export VSR_CUSTOM_PAIR_AGGR_MEM=1`

Please note all these env intend for testing, may cause UB under training.
