### ISSUE TITLE
Test Images Randomized 

### ISSUE THREAD

**Issue by SandLeg** [LoSealL/VideoSuperResolution#52]
So I am trying to run the FRVSR model which is dependent on the previous frame of the image for Video Super Resolution but when I look at my results while testing the image I see that the output images are completely randomized. I noticed that there is a flow parameter in dataset.yaml so I thought that had something to do with it but when I used that I get an error:

line 15, in __init__
    flow = sorted(dataset.flow)
TypeError: 'NoneType' object is not iterable

I would like some clarification on how to run this model and other models using Video Super Resolution for multiple consecutive frames. Any advice is appreciated,

**Comment by LoSealL** [comment]
I write a wiki for how to run FRVSR, you can refer to it first. Flow is for optical flow, not for video SR.

wiki: https://github.com/LoSealL/VideoSuperResolution/wiki/FRVSR

**Comment by LoSealL** [comment]
Expected output:
>$ python eval.py frvsr --cuda --pth ../Results/FRVSR.pth -t vid4 --output_index : --depth -1 --auto_rename
2019-05-23 10:45:53,641 INFO: @LoSealL. Video related ops, nets...
2019-05-23 10:45:56,265 INFO: Total params: 2810661
2019-05-23 10:45:56,842 INFO: Restoring params for frvsr from ../Results/FRVSR.pth.
Test: 100%|##########| 4/4 [00:23<00:00,  5.89s/it]
psnr: 24.567032,

**Comment by SandLeg** [comment]
I just ran it and now it's running everything in order now. I'm training right now but I have another minor issue. It seems the PSNR isn't printed after validation anymore. I don't know if that is intentional or not

**Comment by LoSealL** [comment]
If you want to get PSNR, I recommend you to use `ben.py` under `Train`.
```bash
cd Train
python ben.py --input_dir=../Results/frvsr/VID4 --reference_dir=/path/to/GT/VID4 --enable_psnr
```
The folder structure should be the same.

**Comment by SandLeg** [comment]
> In `eval.py`, if `-t` is passed a dataset name (i.e. `vid4` as samples), it will print PSNR. If it's passed a dir path, no ground truth is given, so no metrics print out.
> 
> The epoch will print only if the pre-trained weights named as `xxx_ep0100.pth` (using epoch 100...).
> It is quite obvious which .pth file is loaded.
This is not during inference I am talking about training. I can't see PSNR scores during training or which epoch I am currently on those were showing up in the previous version that I was using.

**Comment by LoSealL** [comment]
What's your printed information? Does this happen after which commit?

**Comment by LoSealL** [comment]
Seems like the native `print` function doesn't output... I don't know why this happens, may you could try to add `flush=True` to those functions?

They are in `VSRTorch/Framework/Trainer.py`

**Comment by SandLeg** [comment]
> Seems like the native `print` function doesn't output... I don't know why this happens, may you could try to add `flush=True` to those functions?
> 
> They are in `VSRTorch/Framework/Trainer.py`

That's very strange but it seems to work now, thanks again for the assistance.
