### ISSUE TITLE
'.rar' datasets not supported

### ISSUE THREAD

**Issue by sebastianfast** [LoSealL/VideoSuperResolution#53]
When downloading a dataset, it cannot be extracted, because 'rar' is not supported.
   
    python prepare_data.py --filter=91 --data_dir=/home/user/Data

    Do you wish to download 91image? [y/N] y
    Downloading data from http://www.ifp.illinois.edu/~jyang29/codes/ScSR.rar
    24051712/24051007 [==============================] - 56s 2us/step
    Traceback (most recent call last):
      File "prepare_data.py", line 223, in <module>
        main()
      File "prepare_data.py", line 210, in main
        raise TypeError("Unrecognized extension: {}".format(ext))
    TypeError: Unrecognized extension: .rar

**Comment by LoSealL** [comment]
`.rar` is not supported to decompress in python. You can find downloaded files at `/tmp/downloads` or `--download_dir`
