### ISSUE TITLE
How to save image as .bmp or other format instead of .png in inferring stage?

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#57]
How to save image as .bmp or other format instead of .png in inferring stage?

**Comment by LoSealL** [comment]
Hmmm..., PNG is hardcoded for now, you can modify `Callbacks.py`: func `_save_model_predicted_images`

**Comment by HymEric** [comment]
Thank you.

**Comment by LoSealL** [comment]
While PNG is lossless compression, it saves disk usage (a little) than bitmap
