### ISSUE TITLE
I trained sofvsr model. But how to use it to infer RGB image and save as RGB not gray?  

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#59]
In VSRTorch, you say SOF is Y-channel SR with depth=3.
I trained sofvsr model. But how to use it to  save result as RGB not gray in inferring RGB image process?

**Comment by LoSealL** [comment]
add `--output_color=RGB` when using `eval.py` (default is gray)

**Comment by LoSealL** [comment]
UV channel is simply bicubic resized.

**Comment by HymEric** [comment]
When I use --output_color=RGB, Another problem:
![image](https://user-images.githubusercontent.com/26487821/58842848-9094b700-86a2-11e9-8bfb-06f3abe21265.png)

**Comment by HymEric** [comment]
This issue I have addressed. Thank you. It seems the result is not better than edsr.

**Comment by Confusedisprecious** [comment]
ye
