### ISSUE TITLE
EDRN can not train successfully

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#60]
When I try to train EDRN, encountered this: it seems the dimension is not match.

![image](https://user-images.githubusercontent.com/26487821/58806118-09b2f080-8648-11e9-8661-17e6a42050a0.png)

**Comment by LoSealL** [comment]
EDRN is an image SR network. Seems you are trying to train with video data?

**Comment by HymEric** [comment]
I use the image data.
I just change the default scale=1 to scale=4 before train.
![image](https://user-images.githubusercontent.com/26487821/58843184-fa619080-86a3-11e9-8c53-1cf031dbb857.png)

**Comment by LoSealL** [comment]
Oh, I see. `EDRN` is from NTIRE 2019 challenge - Real SR, where its purpose is filtering an image from blur to sharp. `EDRN` itself doesn't contain any upsample module, so changing scale from 1 to 4 needs to modify inside the architecture.

If you are searching for an SOTA image SR network, you can use ESRGAN and set `weights` to `[1, 0, 0]`.

**Comment by HymEric** [comment]
But I saw the **NTIRE 2019 Challenge on Real Image Super-Resolution: Methods and Results** EDRN is a SR model. 
In your NTIRE it seems like including the SR method and denoising method but I couldn't use it correctly.
![image](https://user-images.githubusercontent.com/26487821/58846161-ce004100-86b0-11e9-92ee-d5e2c3333b2e.png)

**Comment by LoSealL** [comment]
NTIRE 2019 SR is a 1:1 scaling challenge

**Comment by HymEric** [comment]
Do you say this competition.
![image](https://user-images.githubusercontent.com/26487821/58847186-a1e6bf00-86b4-11e9-97e8-04bb6d52d136.png)

**Comment by LoSealL** [comment]
Of course. I participated in the challenge and got 13th place in the final.

**Comment by HymEric** [comment]
I'm still confused. The competition conclusion paper said EDRN proposed by IVIP-LAB team got 9th place. And the architectures in paper have upsample operator  to get HR.
![image](https://user-images.githubusercontent.com/26487821/58847549-f50d4180-86b5-11e9-92cd-276dc2df68fa.png)

**Comment by LoSealL** [comment]
You misunderstand, we all use U-net architecture, where in the encoder (at head), pooling to a downsampled feature maps and in the decoder (at tail) upsampled to normal size. The overall resolution is not changed.

**Comment by HymEric** [comment]
Yes, you are right. But can you tell me why it say result output as HR many times in the conclusion paper ? I always think HR is the output of SR work.

**Comment by LoSealL** [comment]
Because in the challenge, we just call "Ground-Truth" as "HR", and its counterpart as "LR". **LR** looks more blurry and **HR** looks clear and sharp. Maybe a little confused :(

**Comment by HymEric** [comment]
Oh. Thank you very much!
