### ISSUE TITLE
Editing custom_pairs

### ISSUE THREAD

**Issue by SandLeg** [LoSealL/VideoSuperResolution#63]
So I am trying to edit the current code in custom_pairs so I can pair 16 input images to a single output image. I am having trouble finding out how the pairing works in the code because it seems like the scenes are paired but not the individual frames. I could use some help finding out how to link the input frames to the single output. I cannot train the default custom_parser because of a dimension mismatch. 

RuntimeError: Expected 4-dimensional input for 4-dimensional weight 32 6 3, but got 3-dimensional input of size [16, 64, 32] instead

Any help would be appreciated.

**Comment by LoSealL** [comment]
**Parser** provides data by `__getitem__`, it should return a list of tuples, where the tuple should be `(x, y, n)`. `x` is regarded as the ground truth, `y` is regarded as inputs and `n` is extra data, here I define `n` as tuple `(data-name, current-index, total-index)`.

Actually, the dimension of `x` and `y` is not defined here, they depend on models. For example, mostly `x` and `y` are 4-D tensors representing [NCHW] data format or 5-D tensors representing [NTCHW] data.

Check what dimension you return and which model you intend to feed.

**Comment by SandLeg** [comment]
> **Parser** provides data by `__getitem__`, it should return a list of tuples, where the tuple should be `(x, y, n)`. `x` is regarded as the ground truth, `y` is regarded as inputs and `n` is extra data, here I define `n` as tuple `(data-name, current-index, total-index)`.
> 
> Actually, the dimension of `x` and `y` is not defined here, they depend on models. For example, mostly `x` and `y` are 4-D tensors representing [NCHW] data format or 5-D tensors representing [NTCHW] data.
> 
> Check what dimension you return and which model you intend to feed.

Thanks, just figured out how to get it to work.
