### ISSUE TITLE
SOFVSR not training on different scales or channels

### ISSUE THREAD

**Issue by SandLeg** [LoSealL/VideoSuperResolution#64]
I am trying to train the SOFVSR model and I run into dimensional errors running whenever I change either the scale to 2 or the channel number to 3. It only runs if the parameters are set to the default value which is the scale set to 4 and channels set to 1. 

Here is the error message at scale=2 and channel=3: 
RuntimeError: Given groups=1, weight of size 64 35 3 3, expected input[16, 17, 32, 32] to have 35 channels, but got 17 channels instead

**Comment by LoSealL** [comment]
Confirm a bug. Fix at `dev`.
