### ISSUE TITLE
Hi! Where can I read the paper<QP-based video restoration network>?

### ISSUE THREAD

**Issue by splinter21** [LoSealL/VideoSuperResolution#72]
It's the paper of QPRN.

I'm also interested in another paper appearing in "VSRTorch-Mldn.py".

Thanks!

**Comment by LoSealL** [comment]
Sorry, but QPRN and MLDN are both designed by myself. MLDN will be reported on **CVPRW 2019 NTIRE Report**, where I participated in NTIRE19 challenge.

QPRN will not be published in a short time, maybe I would release its trained weights in the future.

**Comment by splinter21** [comment]
Oh, I have found the NTIRE2019 paper download page. What's the whole name of MLDN paper?

**Comment by LoSealL** [comment]
It will be *NTIRE 2019 Challenge on Real Image Denoising: Methods and Results*, not published yet.

**Comment by splinter21** [comment]
I've found it. Thanks!
