### ISSUE TITLE
Custom Data Set

### ISSUE THREAD

**Issue by davrocks** [LoSealL/VideoSuperResolution#75]
Hey Loseall!
I am a relative beginner and got a bit lost while reading the readme files pertaining to adding datasets. Essentially, I want to use one of the models to change my photos from medium quality (some are blurry, others are a bit low resolution) to very high quality (they are pictures of upper-halves of people and generally around 400 pixels by 400 pixels). I had a few questions about getting started:

1. Once i download a set of high quality jpg images of random people, do i have to downscale them manually in order to train with them? (Or does the program automatically lower the resolution, run it through the network, and adjust weights automatically) (Also, if possible, do you know any good face datasets with high quality images for this?)

2. If I put the images in this directory: `C:\ProgramData\Anaconda3\envs\py37\VSR\VideoSuperResolution\Data\people_dataset`
then what would i need to change in datasets.yaml for it to be recognized by the program?

e.g: would i create a new entry under `Path:` such as 

`people_dataset: C:\ProgramData\Anaconda3\envs\py37\VSR\VideoSuperResolution\Data\people_dataset`

    
and a new entry `Datasets:` like
```
people_dataset: 
    train: people_dataset
    val: people_dataset  
    test: people_dataset
```

3. is esrgan the best model for improving face quality or is there a better one? (e.g. should i be using a CNN,GAN,AE, or VAE type of model)
4. how many epochs should I run to train a dataset of about 5000-10000 photos?
5. How are the training files saved, and how do I resume training from one of these files? 
6. do you have any other suggestions?

Also, google colab seems to be a cool thing to check out because you can use a tesla t4 gpu for free and train with multiple accounts at once 
I made a very basic notebook for VideoSuperResolution here:
[https://colab.research.google.com/drive/1gTh78EfpZyQczUsUogxxmDPCmoGggoCG](https://colab.research.google.com/drive/1gTh78EfpZyQczUsUogxxmDPCmoGggoCG)

I greatly appreciate the assistance!

**Comment by LoSealL** [comment]
I thought it's quite complicated to explain everything in one thread for a newbie. So let's kick them off one-by-one.

## 1. 
>Once I download a set of high-quality jpg images of random people, do I have to downscale them manually in order to train with them?

The answer is **YES|NO**. In **VSR** we have a data loader. If you choose the default data parser (a parser is how to pre-process input data) then VSR will generate LR image **inside** the data loader (bicubically). However, if you choose another parser (e.g `custom_pairs`), you need to prepare a self-made LR image.

To choose either method depends on your actual task:
- The default one regards reverse *LR* to *HR* a simple task, every `LR` is acquired by `Bicubic(HR, scale)`
- In many real applications, *LR*'s acquisition is more complicated, hence somebody needs to generate a more real HR-LR dataset. In that case, you need a `custom_pairs`

**Comment by LoSealL** [comment]
## 2. 
>If I put the images in this directory: 
>then what would I need to change in datasets.yaml for it to be recognized by the program?

Just edit `datasets.yaml`. I think it's easy to understand. Note there is a `root` entry at the top of the file, and every path is relative to this `root`.

**Comment by LoSealL** [comment]
## 3.
>is esrgan the best model for improving face quality or is there a better one? (e.g. should I be using a CNN, GAN, AE, or VAE type of model)

If you **JUST** want to improve face quality, you'd better retrain a model. The provided pre-trained weights of ESRGAN is for a general purpose.
To choose a proper model, just remember the more parameters it has, the more accurate it generates, and the harder to train.

**Comment by LoSealL** [comment]
## 4.
>how many epochs should I run to train a dataset of about 5000-10000 photos?

Basically, you need 10k+ iterations. The default steps per epoch in VSR setting is 200, so I suggest to train more than 500 epochs for basic usage.
In fact, I usually train 1000-2000 epochs for fine-tuning.

**Comment by LoSealL** [comment]
## 5.
>How are the training files saved, and how do I resume training from one of these files?

VSR automatically save checkpoints in `--save_dir`, by default it's in `../Results/<model-name>/save`

**Comment by LoSealL** [comment]
## 6.
>do you have any other suggestions?

Read documents and [wiki](https://github.com/LoSealL/VideoSuperResolution/wiki) :)

**Comment by davrocks** [comment]
Thanks for the thought out answer! If i use 
```
param:
      parser: custom_pairs
```
at the end of my dataset entry, then which folder would i put the downscaled images in: `train` or `train_pair` ?

**Comment by davrocks** [comment]
Thanks for the extended reply! I created a dataset named `people` and tried to use the custom parser. However, there was an error when i ran `python train.py esrgan --cuda --dataset people --epochs 500`:
```
2019-06-20 19:57:35,400 INFO: LICENSE: ESRGAN is implemented by Xintao Wang. @xinntao https://github.com/xinntao/ESRGAN
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main()
  File "train.py", line 97, in main
    dataset = datasets[flags.dataset.upper()]
KeyError: 'PEOPLE'
```

Here is a copy of my datasets.yaml:
[datasets.txt](https://github.com/LoSealL/VideoSuperResolution/files/3311915/datasets.txt)

**Comment by LoSealL** [comment]
I think this is caused by some images in CelebA is smaller than 128x128. In `esrgan.yml` the `patch_size` is 128, it will randomly crop 128x128 patches from HR images and 32x32 from LR.

Import error is OK because provided `RRDB_GAN.pth` doesn't contain weights for the discriminator. Hence fine-tuning from RRDB_GAN.pth is not a good idea. However, you can start from `RRDB_PSNR.pth`, and you can choose whether to train a discriminator by setting its weights to zero or non-zero.

For example:
```
# PSNR-oriented training, no DNET
python train.py esrgan --cuda --weights=[0.01,1,0] --epochs=100 --dataset=people
# SRGAN-oriented training, with GAN weights 0.001
python train.py esrgan --cuda --weights=[0.01,1,0.001] --epochs=100 --dataset=people
```
This weights is overwriten to `esrgan.yml`.

You could find weights at:
https://drive.google.com/drive/u/0/folders/17VYV_SoZZesU6mbxz2dMAIccSSlqLecY
or
https://pan.baidu.com/s/1-Lh6ma-wXzfH8NqeBtPaFQ?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F

**Comment by davrocks** [comment]
Thanks; so I should start with RRDB_PSNR.pth and go to the gan training with 0.001 for best results?

**Comment by LoSealL** [comment]
In order to train continuously, the best effort is to edit YML file directly.

For who are new to deep learning, I suggest not to touch GAN. Its hyper-parameters highly depend on dataset, which requires master experience to tune it.

You are fine to start with ESRGAN and setting the last weight to zero.

**Comment by davrocks** [comment]
"to start with ESRGAN" you mean starting from RRDB_PSNR.pth right?

**Comment by LoSealL** [comment]
Yes

**Comment by LoSealL** [comment]
I notice that the author provided `RRDB_PSNRx4` and `RRDB_PSNRx4_old_arch`, maybe you should try the old one.

**Comment by davrocks** [comment]
Would PSNR training provide a good result though? or should I switch to another model that is easier to train

**Comment by LoSealL** [comment]
Actually that depends on what you want. You could first use RRDB_PSNRx4 to generate SR faces and check the quality.

In my view, PSNR-oriented model is fine enough to beat traditional methods. You could set GAN weights to a reasonably small value (i.e. 1e-4) to see what gonna to happen compared to `RRDB_PSNRx4`.

**Comment by davrocks** [comment]
Thanks, I will try the psnr first :)

**Comment by davrocks** [comment]
Hey, everything seems to be going smoothly; I ended up going for the old_arch because it could load the rrdb parameters (and it started out with a lower image loss). Here are the logs: 
[Old Arch.txt](https://github.com/LoSealL/VideoSuperResolution/files/3316274/Old.Arch.txt)
[New Arch.txt](https://github.com/LoSealL/VideoSuperResolution/files/3316275/New.Arch.txt)


Now, I was just wondering what the four .pth files in the ESRGAN save folder are for, and which one i should load for using on eval.py. (the names are dnet_ep0001.pth, optd.pth, optg.pth, and rrdb_ep0001.pth)

**Comment by LoSealL** [comment]
As I expected, you should stick to old arch weights.

If you do not provide `--pth` , then eval will automatically restore weights from `save` folder. For multiple PTH, you only need to load `rrdb_epxxxx.pth` to do inference, and don't set `--pth` explicitly to resume training.

For the last question: sure, you can do that. The only thing you will notice is that you may need to seek a proper weight in trial and error.

**Comment by davrocks** [comment]
Hello again!
When would be a good time to switch from PSNR training to GAN training by changing the weights in the yml? Is there a certain avg loss per epoch, number of epochs, or other indication? Right now I am at 252 epochs and the learning rate just decreased from 0.0001 to 0.00005.

**Comment by LoSealL** [comment]
Yeah, it's totally empirical...
ASAIK, you have to trail and error once a model...
Empirically, if GAN weight is non-zero, the evaluation PSNR would drop a delta `P`, and I would monitor the number of `P`. The higher of the weight, the more it drops.
The best range of `P` may be [2-5] dB, which guides me on how to set a proper weight value.

**Comment by davrocks** [comment]
Thanks! so about what epoch should I be switching to GAN?

**Comment by LoSealL** [comment]
I thought you could switch right now

**Comment by davrocks** [comment]
Cool thx

**Comment by davrocks** [comment]
Where is this P value?
```
2019-06-25 03:15:43,671 INFO: LICENSE: ESRGAN is implemented by Xintao Wang. @xinntao https://github.com/xinntao/ESRGAN
2019-06-25 03:15:49,888 INFO: Total params: 77223884
2019-06-25 03:16:22,734 INFO: Restoring params for rrdb from /usr/local/VideoSuperResolution/Results/esrgan/save/rrdb_ep0328.pth.
2019-06-25 03:16:22,931 WARNING: trying to restore state for optimizer optd, but failed.
2019-06-25 03:16:23,138 INFO: Fitting: [DNET][RRDB]
| 2019-06-25 03:17:31 | Epoch: 329/500 | LR: 5e-05 |
100% 200/200 [06:24<00:00,  1.62s/batch, loss=01.05198, image=00.02711, loss_g=06.79467, loss_d=00.00227]
| Epoch average loss = 1.148688 |
| Epoch average image = 0.029503 |
| Epoch average loss_g = 4.285503 |
| Epoch average loss_d = 0.380308 |
Test: 100% 10/10 [00:00<00:00, 12.14it/s]
psnr: 26.229016, 
| 2019-06-25 03:24:13 | Epoch: 330/500 | LR: 5e-05 |
```

**Comment by LoSealL** [comment]
evaluation PSNR has a relatively large fluctuation, you could observe training loss for example.
And another thing matters is that keep loss of D-net away from being zero.

**Comment by davrocks** [comment]
And D-net loss is loss_d right?

**Comment by LoSealL** [comment]
Without being zero. It looks normal so far.

**Comment by davrocks** [comment]
What should I do if my loss_d becomes 0?

**Comment by LoSealL** [comment]
1. Decreasing the learning rate
2. Review your dataset, is this dataset too easy for the discriminator and too hard for the generator?
3. Replay with default ESRGAN, and DIV2K dataset, see if you can train a vanilla model from scratch.
