### ISSUE TITLE
Pretrained weights for CARN

### ISSUE THREAD

**Issue by sebastianfast** [LoSealL/VideoSuperResolution#77]
Hi

I noticed the pretrained weights you supply for CARN based on TF are not for TF, but for Torch. Both weight-links in `prepare_data.py` have the same file contents. Did you by mistake upload Torch weights for the TF model?

Anyhow, I have tried the Torch weights for the Torch Carn model and I'm getting the following error when trying to load the model:

    2019-06-25 14:24:11,220 INFO: Total params: 1111899
    2019-06-25 14:24:11,226 INFO: Restoring params for carn from /<path>/VideoSuperResolution/Results/carn.pth.
    Error(s) in loading state_dict for Net:
        Missing key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias", "upsample.up.body.3.weight", "upsample.up.body.3.bias". 
        Unexpected key(s) in state_dict: "upsample.up2.body.0.weight", "upsample.up2.body.0.bias", "upsample.up3.body.0.weight", "upsample.up3.body.0.bias", "upsample.up4.body.0.weight", "upsample.up4.body.0.bias", "upsample.up4.body.3.weight", "upsample.up4.body.3.bias". 
    2019-06-25 14:24:11,237 WARNING: Couldn't restore state for carn from /<path>/VideoSuperResolution/Results/carn.pth.
    Infer: 100%|##########| 30/30 [00:06<00:00,  4.43it/s]

I'm using your latest release.

Thanks for the work you've put in this.

**Comment by LoSealL** [comment]
https://github.com/LoSealL/VideoSuperResolution/wiki/CARN

**Comment by sebastianfast** [comment]
I downloaded the CARN weights as shown in the link with:

    python prepare_data.py --filter Tcarn

Then I ran the model with:

    python <VSR_dir>/VSRTorch/eval.py carn --test <test_dir> --pth <VSR_dir>/Results/carn.pth --save_dir <save-dir> --cuda --output_color RGB

I got the following output:

    2019-06-27 08:02:33,534 INFO: LICENSE: CARN is implemented by Namhyuk Ahn. @nmhkahn https://github.com/nmhkahn/CARN-pytorch
    2019-06-27 08:02:36,368 INFO: Total params: 1111899
    2019-06-27 08:02:36,375 INFO: Restoring params for carn from <path>/VideoSuperResolution/Results/carn.pth.
    Error(s) in loading state_dict for Net:
        Missing key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias", "upsample.up.body.3.weight", "upsample.up.body.3.bias". 
	Unexpected key(s) in state_dict: "upsample.up2.body.0.weight", "upsample.up2.body.0.bias", "upsample.up3.body.0.weight", "upsample.up3.body.0.bias", "upsample.up4.body.0.weight", "upsample.up4.body.0.bias", "upsample.up4.body.3.weight", "upsample.up4.body.3.bias". 
    2019-06-27 08:02:36,387 WARNING: Couldn't restore state for carn from <path>/VideoSuperResolution/Results/carn.pth.
    Infer: 100%|##########| 30/30 [00:05<00:00,  6.01it/s]

Also, referencing the following code from your link:

    cd VSRTorch
    python eval.py esrgan --cuda --pth ../Results/carn.pth --multi_scale 1 -t ../Data/Set5_SR/Set5/image_SRF_4/*LR.png

Are you trying to run ESRGAN with CARN weights? I tried this and it is not working. I also tried running ESRGAN with the weights supplied by prepare_data.py (Results/RRDB_GAN.pth) and got a similar error to the one I got when trying to run CARN.

**Comment by LoSealL** [comment]
@sebastianfast Sorry for confusing you.

There is a typo mistake in wiki page.
Use:
`python eval.py carn --cuda --pth ../Results/carn.pth --multi_scale 1 -t ../Data/Set5_SR/Set5/image_SRF_4/*LR.png`

The model name should be `carn`. and using provided weights you should add `--multi_scale=1`.

**Comment by LoSealL** [comment]
If you are not running from local directory, then you should also add an argument `-p <VSR>/VSRTorch/Parameters/carn.yml` to specify parameter file.
