### ISSUE TITLE
Where should I download the pre-train model?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [LoSealL/VideoSuperResolution#8]
Hi, here. I wanna apply your fantastic to testing some SOTA SR works. However I cannot find pre-train model(s) included. Could you please tell me how I download and apply the pre-train models? Thx for your kindness.

**Comment by LoSealL** [comment]
Hi you can use `prepare_data.py` in root folder. Anything unclear, just feel free to let me know.

**Comment by yuqing-liu-dut** [comment]
Thx very much!
