### ISSUE TITLE
some problems for starting

### ISSUE THREAD

**Issue by jerry1618** [LoSealL/VideoSuperResolution#87]
Hi, Thank you for your works and I have some problems when starting this project in windows 8. The error log is showed below.  And I changed the default dir as below, but the same happened;
What's more, I have some problem to visit google website in my enviroment.  Do you has any other  way to get the resource?

_DEFAULT_DATASET_PATH = 'E:/project/AI/code/VideoSuperResolution-master/tmp/data/datasets' #'/mnt/data/datasets'
_DEFAULT_DOWNLOAD_DIR = 'E:/project/AI/code/VideoSuperResolution-master/tmp/downloads' #'/tmp/downloads'
_DEFAULT_WEIGHTS_DIR = './Results'

Thank you!

(tensorflow) E:\project\AI\code\VideoSuperResolution-master>python prepare_data.
py --filter espcn SET5
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
CreateFile() Error: 2
download_dir: {} E:/project/AI/code/VideoSuperResolution-master/tmp/downloads
Do you wish to download SET5? [y/N] y
Do you wish to download espcn.tar? [y/N] y
Downloading data from https://github.com/LoSealL/Model/releases/download/espcn/e
spcn.tar.gz
CreateFile() Error: 2
CreateFile() Error: 2
Unable to get file espcn.tar.gz
Downloading data from https://uofi.box.com/shared/static/kfahv87nfe8ax910l85dksy
l2q212voc.zip
CreateFile() Error: 2
CreateFile() Error: 2
Unable to get file SET5.zip

**Comment by LoSealL** [comment]
What's your tensorflow version (including keras version)?
Do you have R/W permission? (Especially, can you call `Path.mkdir` by yourself?)

**Comment by jerry1618** [comment]
Hi, my tensorflow version is 2.0.0-beta1 and keras version is 2.2.5. I can use mkdir command to create folds in anaconda prompt. And I can find the new created folds name "E:\project\AI\code\VideoSuperResolution-master\tmp\downloads"

**Comment by LoSealL** [comment]
Support for TF2 is not tested at all. I expect to use TF<=1.14
