### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by greatAznur** [LoSealL/VideoSuperResolution#88]
for the comande 
python prepare_data.py --filter vespcn vid4

i have th link but i past in my broswer
hi have this mesage 
Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

....

**Comment by greatAznur** [comment]
ok i have change the link by https://drive.google.com/open?id=<id> in prepardata.py

**Comment by greatAznur** [comment]
ok is not fonctional  i have downlad   all packet i want and i create my website for donwolad

**Comment by wang-zj-1** [comment]
> 好的，我已经通过prepardata.py中的https://drive.google.com/open?id=更改了链接

现在还是需要登录哦

**Comment by epiccipe** [comment]
Hi all,

Has this issue been resolved? 
I am experiencing the same issue. Is there another site from which we can download the models?

**Comment by LoSealL** [comment]
@epiccipe Most models are shared with Google Drive. You can use drive id to access the link directly.

Only a part of models are uploaded on Github, you can find them on https://github.com/LoSealL/Model/releases
