### ISSUE TITLE
hi,Which paper is the corresponding paper for this code?

### ISSUE THREAD

**Issue by houqian2180320171** [LoSealL/VideoSuperResolution#89]

**Comment by LoSealL** [comment]
It's listed on the front page's README.md

**Comment by houqian2180320171** [comment]
Hi,I didn't find a link to the paper in the place you said. Can you re-issue the paper link?Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Tang, Wenyi"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 晚上6:07
收件人: "LoSealL/VideoSuperResolution"<VideoSuperResolution@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LoSealL/VideoSuperResolution] hi,Which paper is thecorresponding paper for this code? (#89)




It's listed on the front page's README.md

**Comment by LoSealL** [comment]
In the table: https://github.com/LoSealL/VideoSuperResolution#network-list-and-reference-updating
In col **Published**, each is a link to the paper.

**Comment by houqian2180320171** [comment]
Hi,I have already opened the link you just sent. Can you tell me which model it corresponds to? I want to look at the paper first, then look at the specific code.
Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Tang, Wenyi"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 晚上7:21
收件人: "LoSealL/VideoSuperResolution"<VideoSuperResolution@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LoSealL/VideoSuperResolution] hi,Which paper is thecorresponding paper for this code? (#89)




In the table: https://github.com/LoSealL/VideoSuperResolution#network-list-and-reference-updating
 In col Published, each is a link to the paper.

**Comment by LoSealL** [comment]
For example:

Model | Published | Code* | VSR (TF)** | VSR (Torch) | Keywords | Pretrained
-- | -- | -- | -- | -- | -- | --
SRCNN | [ECCV14](https://arxiv.org/abs/1501.00092) | -, Keras | Y | Y | Kaiming | √

This means model **SRCNN** is originally from ECCV2014, and you can click *ECCV14* to open the link to the paper of SRCNN.

**Comment by houqian2180320171** [comment]
Thank you very much




------------------ 原始邮件 ------------------
发件人: "Tang, Wenyi"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 晚上7:33
收件人: "LoSealL/VideoSuperResolution"<VideoSuperResolution@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LoSealL/VideoSuperResolution] hi,Which paper is thecorresponding paper for this code? (#89)




For example:
    Model Published Code* VSR (TF)** VSR (Torch) Keywords Pretrained 
    SRCNN ECCV14 -, Keras Y Y Kaiming √ 
   
This means model SRCNN is originally from ECCV2014, and you can click ECCV14 to open the link to the paper of SRCNN.

**Comment by houqian2180320171** [comment]
Hi,Can you recommend any papers about video super-resolution?




------------------ 原始邮件 ------------------
发件人: "Tang, Wenyi"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 晚上7:33
收件人: "LoSealL/VideoSuperResolution"<VideoSuperResolution@noreply.github.com>;
抄送: "上善若水"<2570725376@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LoSealL/VideoSuperResolution] hi,Which paper is thecorresponding paper for this code? (#89)




For example:
    Model Published Code* VSR (TF)** VSR (Torch) Keywords Pretrained 
    SRCNN ECCV14 -, Keras Y Y Kaiming √ 
   
This means model SRCNN is originally from ECCV2014, and you can click ECCV14 to open the link to the paper of SRCNN.

**Comment by LoSealL** [comment]
EDVR, DUF and FRVSR are all good to read
