### ISSUE TITLE
[RE] Fail to run SRCNN/VDSR/DRRN/DRCN?

### ISSUE THREAD

**Issue by LoSealL** [LoSealL/VideoSuperResolution#9]
You may got error like this:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [16,12,12,1] vs. [16,48,48,1] 
 [[{{node loss/absolute_difference/Sub}} = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](vdsr/add, _arg_label/hr_0_2/_7)]] 
 [[{{node loss/total_loss/_15}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0",send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1159_loss/total_loss", tensor_type=DT_FLOAT,_device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

All these 4 models share one same perception: They run directly on HR space, which means (usually) a bicubic upsampler is applied to LR image and feed directly into the network.
This is done by code like `bic = bicubic_rescale(self.inputs_preproc[-1], self.scale)`.

Due to some history reasons, sometimes I don't intend to use bicubic filter implemented in tensorflow (pixel unaligned, pixel shift and negative pixels, [[1]](https://github.com/tensorflow/tensorflow/issues/10722) [[2]](https://github.com/tensorflow/tensorflow/issues/19880)). Hence I offer an option to use bicubic filter from PIL.Image. This is done by commented out `bic = bicubic_rescale(self.inputs_preproc[-1], self.scale)` (or just delete), and add `--add_custom_callbacks=upsample` to `run.py`.

You get this error because in some old version I forget to recover back the commented code, and you don't add `--add_custom_callbacks=upsample` when training models, so image size is not matched.

I checked and fixed the problem for SRCNN/VDSR/DRCN/DRRN today, and leave an argument `custom_upsample` in the yaml to config:
    - If `custom_upsample` is False (default), it uses bicubic filter from `tf.image.resize_bicubic`;
    - If `custom_upsample` is True, then `--add_custom_callbacks=upsample` must be added to `run.py`. _upsample_ is defined in `custom_api.py`

**Comment by liweifdu** [comment]
Thank you, setting the custom_upsample as true ,and adding --add_custom_callbacks=upsample are useful.
