### ISSUE TITLE
frame is empty.

### ISSUE THREAD

**Issue by wuwei6** [LoSealL/VideoSuperResolution#92]
Hey, thank for your sharing. When I finish training and start testing, it will appear 'frame is empty'. Can you help to solve that? 

frames is empty. [size=-1]

Test: 0it [00:00, ?it/s]
frames is empty. [size=-1]

**Comment by LoSealL** [comment]
Following the guide here https://github.com/LoSealL/VideoSuperResolution/blob/master/Data/README.md

Assign your own database URL.

**Comment by wuwei6** [comment]
> Following the guide here https://github.com/LoSealL/VideoSuperResolution/blob/master/Data/README.md
> 
> Assign your own database URL.

**Comment by wuwei6** [comment]
> Following the guide here https://github.com/LoSealL/VideoSuperResolution/blob/master/Data/README.md
> 
> Assign your own database URL.

Sorry. Databse URL in my area cannot be opened. What should I do if I want to complete training and testing offline?
