### ISSUE TITLE
frame is empty.

### ISSUE THREAD

**Issue by wuwei6** [LoSealL/VideoSuperResolution#93]
Following the guide here https://github.com/LoSealL/VideoSuperResolution/blob/master/Data/README.md

Assign your own database URL.

Sorry, I seem to have accidentally deleted the last question. I can't open your dataset URL in my area, So I don't know how to assign my own database URL. May I ask what should I do if I want to train and test off-line?

**Comment by LoSealL** [comment]
You misunderstood.

If you have already prepared your off-line dataset, what you need to do is:

- Open Data/dataset.yml
- Add an entry under `Path` to describe your data url
- Add a binding under `Dataset` to describe your training/testing/validating data

**Comment by blackhumor22** [comment]
Hello, I have the same problem, I have followed the path of dataset.yml to add. The problem is still not solved, can you give me an example? For example the complete path of set5 data, thank you.

**Comment by wuwei6** [comment]
Thank you for your help! I use the DRRN and the VDSR model for training. I got the test results by using the set5 dataset, but it is only 0.03 higher than the PSNR calculated by bicubic interpolation. MAE is about 120. I added the epoch, but it didn't change. Should I change the parameters?

**Comment by LoSealL** [comment]
Closed for a long time no response. Reopen if you needed.
