### ISSUE TITLE
Training of TecoGAN hasn't been verified

### ISSUE THREAD

**Issue by zZFh** [LoSealL/VideoSuperResolution#95]
Hi, I tried to train and test the TecoGAN model, but it doesn't seem to be supported. Have you completed this part?

**Comment by LoSealL** [comment]
not yet

**Comment by zZFh** [comment]
thanks!  Could you tell me which system in your training?  I found that the format of the compressed package is tar.gz, which is on linux. But my system is window, I decompressed it with haoya after downloaded. Because the vgg_19.ckpt was not demage, so I direct ran the runGAN.py 3 in cmd and then I get back this a error message.

**Comment by zZFh** [comment]
oh, thank you very much!  what has and has not yet been implemented now?

**Comment by LoSealL** [comment]
The TecoGAN networks and training are implemented followed by the original paper. But the hyper-parameters are not tuned so the training will not converge.

Now the author open-sourced his codes including training script. You can refer his [code](https://github.com/thunil/TecoGAN)
